name: learnfrog_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  crypto: ^3.0.3
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  dart_frog_cli: ^1.2.3
  equatable: ^2.0.5
  firedart: ^0.9.8
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.15.0
  mongo_dart: ^0.10.3
  postgres: ^3.2.1
  redis: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
